// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiVendorShop.Data;

#nullable disable

namespace MultiVendorShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MultiVendorShop.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MultiVendorShop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryAddress = "12/A Nawala Road, Nugegoda",
                            Email = "amara@example.lk",
                            FullName = "Amara Perera",
                            PasswordHash = "$2a$11$/Zy.GNNiH7rGCDAfzauMMe/CP70r.xsGOOYKcMuJR4cLIDMVyvXhm",
                            Phone = "+94 71 234 5678"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryAddress = "56 Galle Road, Mount Lavinia",
                            Email = "kasun@example.lk",
                            FullName = "Kasun Silva",
                            PasswordHash = "$2a$11$cAslN/NvsF.jJ7s17P0aXOO8jOz1oqq0Kj1sfYP9ivParki.mudnm",
                            Phone = "+94 77 345 6789"
                        });
                });

            modelBuilder.Entity("MultiVendorShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MultiVendorShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VendorId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MultiVendorShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Spices",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium true cinnamon sticks from Matale.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Ceylon Cinnamon (100g)",
                            Price = 850.00m,
                            Stock = 200,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Spices",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sun-dried black pepper, Kandy estate.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Black Pepper Whole (250g)",
                            Price = 1200.00m,
                            Stock = 150,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Spices",
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aromatic green cardamom pods.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Cardamom Green (50g)",
                            Price = 950.00m,
                            Stock = 100,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Spices",
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pure turmeric, no additives.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Turmeric Powder (200g)",
                            Price = 420.00m,
                            Stock = 300,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Universal fast charger with GaN technology.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "USB-C Fast Charger 65W",
                            Price = 3500.00m,
                            Stock = 75,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TWS earbuds, noise cancellation, 24hr battery.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Wireless Bluetooth Earbuds",
                            Price = 8900.00m,
                            Stock = 50,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-speed 4K@60Hz HDMI 2.0 cable.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "HDMI Cable 2m (4K)",
                            Price = 1450.00m,
                            Stock = 120,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dual USB-A + USB-C, 20W fast charge.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Portable Power Bank 20000mAh",
                            Price = 12500.00m,
                            Stock = 35,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 9,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traditional hand-waxed batik in vibrant colours.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Handmade Batik Sarong",
                            Price = 2800.00m,
                            Stock = 40,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 10,
                            Category = "Home Decor",
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handcrafted cushion covers, 45x45cm.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Batik Cushion Cover (Set of 2)",
                            Price = 1900.00m,
                            Stock = 60,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 11,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight pure silk scarf, hand-batik printed.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Silk Batik Scarf",
                            Price = 3200.00m,
                            Stock = 30,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 12,
                            Category = "Home Decor",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Signed artwork, 90x60cm, ready to hang.",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Batik Wall Hanging (Large)",
                            Price = 5500.00m,
                            Stock = 15,
                            VendorId = 3
                        });
                });

            modelBuilder.Entity("MultiVendorShop.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Pettah Market, Colombo 11",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "spice@ceylon.lk",
                            IsActive = true,
                            PasswordHash = "$2a$11$NXGA/IVGp7eVyYfQZ08WF.LmyFhDVPYXcSBCxCEXmZ7x1YAlzFKqi",
                            Phone = "+94 11 234 5678",
                            ShopName = "Ceylon Spice House"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Majestic City, Bambalapitiya, Colombo 04",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@lankatech.lk",
                            IsActive = true,
                            PasswordHash = "$2a$11$vJqNa6efUH.CETLToeAZuep7wLwaxcG9jDJ12pNbI8wn4r8Ru4R.q",
                            Phone = "+94 77 456 7890",
                            ShopName = "Lanka Electronics Hub"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Kandy Road, Peradeniya",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hello@batikandbeyond.lk",
                            IsActive = true,
                            PasswordHash = "$2a$11$cdDq3r/CDQjYTrhIAvlnme9wTU8L3NyTYk53XuPpolEWO557E7OnO",
                            Phone = "+94 81 567 8901",
                            ShopName = "Batik & Beyond"
                        });
                });

            modelBuilder.Entity("MultiVendorShop.Models.CartItem", b =>
                {
                    b.HasOne("MultiVendorShop.Models.Customer", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MultiVendorShop.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MultiVendorShop.Models.Order", b =>
                {
                    b.HasOne("MultiVendorShop.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MultiVendorShop.Models.OrderItem", b =>
                {
                    b.HasOne("MultiVendorShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MultiVendorShop.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MultiVendorShop.Models.Vendor", "Vendor")
                        .WithMany("OrderItems")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("MultiVendorShop.Models.Product", b =>
                {
                    b.HasOne("MultiVendorShop.Models.Vendor", "Vendor")
                        .WithMany("Products")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("MultiVendorShop.Models.Customer", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MultiVendorShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MultiVendorShop.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MultiVendorShop.Models.Vendor", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
